### PR TITLE
Ej redesign

### LINKED ISSUE #73: redesign EJ page to include two maps side by side
One map would show the selected socio-economic indicator and PWS information. The other map would show a selected environmental indicator and PWS information. This would enable more direct EJ insights.

### PR DESCRIPTION
**Pull request by ericnost**
fixes #73

### CODE REVIEW

**Comment by Frijol** [comment]
This is super cool! Couple of issues though: 
* [ ] Maps not draggable/zoomable
* [ ] Color bars are too big, running into the next column (I really want a way for these and the maps to just be 100% width!)
* [ ] The definitions are different sizes, which makes the maps uneven
image

**Comment by Frijol** [comment]
Leaving the interactivity issue to you since I assume it's something simple you already know

**Comment by ericnost** [comment]
> Leaving the interactivity issue to you since I assume it's something simple you already know

Yea, I did this on purpose. I don't think the user needs to drag around all over the place, if all we're showing is their area of interest. Likewise they don't necessarily need to zoom out (but *maybe* in). The "problem" with zoom is that it feels weird if you zoom in on one map but the other doesn't zoom in at the same time, and that's not "simple" for me to figure out. But I'll make an issue out of it and we'll see what comes of it?

**Comment by ericnost** [comment]
Looks great, thank you!

**Pull request merged**
