### PR TITLE
Adding context to pages

### PR DESCRIPTION
**Pull request by Frijol**

### CODE REVIEW

**Comment by ericnost** [comment]
@Frijol Just checking in - do you need my review yet?

**Comment by Frijol** [comment]
Oh, either way! I try to leave the pull requests in draft form unless they're ok to merge, but will keep adding to this one too.

**Comment by Frijol** [comment]
Ok, I think this PR now includes every major context addition I have an issue open for!

**Comment by ericnost** [comment]
Will take a look and then merge!

**Review by ericnost — APPROVED** [review]
This is great! I think there is still some of the writing to pin down, like the "other aspects to be determined" language and the instructions on the Welcome page, but that can come later after functionality and other elements are settled.

**Pull request merged**
