### PR TITLE
restores ej definitions

### LINKED ISSUE #54: Lost the human-readable names for EJ indicators
Wait, we still want this dictionary as well! "ejvar" is the behind-the-scenes variable, "ej_dict" is the human-readable name for the category, and "ejdefs" is the longform description

_Originally posted by @Frijol in https://github.com/ericnost/streamlit_test/pull/52#discussion_r1266166691_

### PR DESCRIPTION
**Pull request by ericnost**
Fixes #54

### CODE REVIEW

**Comment by ericnost** [comment]
@Frijol not much of a change here, just restoring what I broke. In addition (or maybe it was like this), I changed the map popup to be the shorthand variable name not its behind the scenes name. So "% people of color" instead of "MINORPCT"

**Comment by Frijol** [comment]
Probably should have done this in a separate PR, but added to yours instead:
* Typo fixes
* Rearranged page in a way I think makes more sense
* Matched color scale width to map width
* Added spacing in the map popup labels

Merge if you like it!

**Review by Frijol — APPROVED** [review]

**Comment by ericnost** [comment]
Awesome! Thank you for getting out the map popup labels. I wracked my brain about those....

I just made some minor edits (making sure we specific block group not block, adding the colorscale width property to the lead lines page).

**Comment by Frijol** [comment]
Yeah, it took a shockingly long time to get that space in there!

**Pull request merged**
