### PR TITLE
Unreverts removal of the nice page switching buttons

### PR DESCRIPTION
**Pull request by Frijol**
Ha I'm not sure what the Github-semantic way to do this is but here is the version with nice page-switch versions working:

image

I'm assuming it breaks in production because I added a new package (it's in the Pipfile). Is there anything special I need to do for that?

### CODE REVIEW

**Comment by ericnost** [comment]
@Frijol Amazing! I think I would just need to log into Streamlit and reboot the app. Let me review then I'll merge and reboot.

**Review by ericnost — APPROVED** [review]
I love the buttons! I think it gives us flexibility in what approach to navigation to take going forward (buttons for a very linear flow-through, buttons+side panel, etc.)

The only issue I saw was that the first button (Next: Statewide Overview) produces a blank page before loading. Most other pages say "Running" in the upper right hand corner or have other context available. I think it's ok - it's not a very long load - but something to be aware of.

**Comment by ericnost** [comment]
@Frijol Buttons are live @ https://sdwa-eew.streamlit.app/

Rebooting the app requires a log in to the Streamlit cloud here https://share.streamlit.io/

I don't think there's a way for me to add you to the app there, but my understanding is that if you have edit permissions on the Github repo the cloud app pulls from, you should be able to manage it on Streamlit as well (given that you link your Streamlit account with your Github account).

I'm also just happy to do the rebooting myself.

**Comment by Frijol** [comment]
Yay looks good!

**Pull request merged**
