### PR TITLE
Spells out acronyms and modifies bar chart to accommodate

### PR DESCRIPTION
**Pull request by Frijol**
Towards https://github.com/ericnost/streamlit_test/issues/10

### CODE REVIEW

**Comment by Frijol** [comment]
image
image

**Comment by Frijol** [comment]
image

**Comment by Frijol** [comment]
image

**Comment by Frijol** [comment]
This is ready now! Fixes https://github.com/ericnost/streamlit_test/issues/10

**Review by ericnost — COMMENTED** [review]
@Frijol This looks pretty good.

I commited some minor changes to sort the table and chart on the Overview page. We could do something similar for the other pages eventually....

~🚨 I noticed that in this PR/branch, the SDWA_Violations page is broken. Specifically, drawing a box will load markers to the map, but it won't actually load the chart and table.

I'm not sure why that is. The live version at https://sdwa-eew.streamlit.app/SDWA_Violations doesn't experience this problem, and the code looks exactly the same as what we have in this branch...

So I'm a bit lost...do you experience this issue too?~

edit: the commit below fixes this, I think.

**Comment by ericnost** [comment]
so I think it's ready to merge and will do so

**Pull request merged**
