### PR TITLE
Custom cluster icons and simpler tooltips

### PR DESCRIPTION
**Pull request by Frijol**
Working on https://github.com/ericnost/streamlit_test/issues/112 and I think I got it but the server seems to be down so can't test

### CODE REVIEW

**Comment by ericnost** [comment]
@Frijol Nice! This is what I get when I run it:

image

is that expected, the little white squares? 

We should also add `showCoverageOnHover=False` to remove the blue polygons that appear when hovering over a cluster.

**Comment by ericnost** [comment]
Whenever we get the styling correct on the violations page, we'd probably want to do the same for the other pages with marker clusters (all except Lead and Watershed?) plus maybe do it for the Statewide Overview (not currently clustered, but maybe should be).

**Comment by ericnost** [comment]
Fixes #121

**Comment by Frijol** [comment]
Agreed. And ha, no, that's not the expected behavior, but time to dive back in...

**Comment by Frijol** [comment]
YAY! That was a shocking amount of work but I feel good about this: 
image

**Comment by Frijol** [comment]
Slippy map now doesn't try to display all the websites of the water systems, keeps it a bit simpler 
image

**Pull request merged**
